# Generated by Django 2.2.22 on 2021-09-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('', 'Избери'), ('Бежов', 'Бежов'), ('Бордо', 'Бордо'), ('Бял', 'Бял'), ('Виолетов', 'Виолетов'), ('Жълт', 'Жълт'), ('Зелен', 'Зелен'), ('Кафяв', 'Кафяв'), ('Оранжев', 'Оранжев'), ('Сив', 'Сив'), ('Сребърен', 'Сребърен'), ('Червен', 'Червен'), ('Черен', 'Черен'), ('Лилав', 'Лилав'), ('Розов', 'Розов'), ('Светло зелен', 'Светло зелен'), ('Светло син', 'Светло син'), ('Тъмно зелен', 'Тъмно зелен'), ('Тъмно сив', 'Тъмно сив'), ('Тъмно син', 'Тъмно син')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='displacement',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='euro_standart',
            field=models.CharField(choices=[('', 'Избери'), ('EURO 1', 'EURO 1'), ('EURO 2', 'EURO 2'), ('EURO 3', 'EURO 3'), ('EURO 4', 'EURO 4'), ('EURO 5', 'EURO 5'), ('EURO 6', 'EURO 6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='month',
            field=models.CharField(choices=[('', 'Избери'), ('Януари', 'Януари'), ('Февруари', 'Февруари'), ('Март', 'Март'), ('Април', 'Април'), ('Май', 'Май'), ('Юни', 'Юни'), ('Юли', 'Юли'), ('Август', 'Август'), ('Септември', 'Септември'), ('Октомври', 'Октомври'), ('Ноември', 'Ноември'), ('Декември', 'Декември')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='run',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(choices=[('', 'Избери'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=4),
        ),
    ]
