# Generated by Django 2.2.22 on 2021-10-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210909_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors_type',
            field=models.CharField(choices=[('', 'Избери'), ('2/3', '2/3'), ('4/5', '4/5')], default='2/3', max_length=5),
            preserve_default=False,
        ),
    ]
